"""empty message

Revision ID: 0905f8ffe940
Revises: c2842a451860
Create Date: 2021-01-20 06:32:11.485098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0905f8ffe940'
down_revision = 'c2842a451860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webinfo')
    # ### end Alembic commands ###
