"""empty message

Revision ID: 2e2e83eb23b3
Revises: e9b237d7ebf3
Create Date: 2021-01-20 08:39:36.940075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e2e83eb23b3'
down_revision = 'e9b237d7ebf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_researches', 'research_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_researches', sa.Column('research_type', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
