"""empty message

Revision ID: 36f330baa166
Revises: 2e2e83eb23b3
Create Date: 2021-01-22 17:21:16.450510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36f330baa166'
down_revision = '2e2e83eb23b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', mysql.VARCHAR(length=4), nullable=True))
    # ### end Alembic commands ###
