"""empty message

Revision ID: 373b4f80094f
Revises: 
Create Date: 2021-01-12 01:43:07.227539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373b4f80094f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specific_periods', 'content')
    # ### end Alembic commands ###
