"""empty message

Revision ID: 40f476a177c9
Revises: 91885e4822c5
Create Date: 2021-01-25 18:18:25.885924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f476a177c9'
down_revision = '91885e4822c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'title')
    # ### end Alembic commands ###
