"""empty message

Revision ID: 7c65e57f502d
Revises: c1b2addefc38
Create Date: 2021-01-15 15:25:45.003048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c65e57f502d'
down_revision = 'c1b2addefc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('COPI_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specific_period_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('COPI_content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specific_period_id'], ['specific_periods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('COPI_project')
    # ### end Alembic commands ###
