"""empty message

Revision ID: 896b4e42810f
Revises: 6016cd35e1af
Create Date: 2021-01-25 18:20:35.986962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '896b4e42810f'
down_revision = '6016cd35e1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('project_title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specific_periods', 'project_title')
    # ### end Alembic commands ###
