"""empty message

Revision ID: 8a41d475a3c5
Revises: 36f330baa166
Create Date: 2021-01-25 04:51:12.875779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a41d475a3c5'
down_revision = '36f330baa166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_hash')
    # ### end Alembic commands ###
