"""empty message

Revision ID: 91885e4822c5
Revises: 417b2d50b439
Create Date: 2021-01-25 18:18:11.228633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91885e4822c5'
down_revision = '417b2d50b439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'title')
    op.add_column('news', sa.Column('title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'title')
    op.add_column('events', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    # ### end Alembic commands ###
