"""empty message

Revision ID: 9431ad0969c1
Revises: a490af0bd60e
Create Date: 2021-01-12 09:57:22.111185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9431ad0969c1'
down_revision = 'a490af0bd60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('project_link', sa.String(length=256), nullable=True))
    op.add_column('specific_periods', sa.Column('project_nation', sa.String(length=64), nullable=True))
    op.drop_column('specific_periods', 'nation')
    op.drop_column('specific_periods', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('link', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('specific_periods', sa.Column('nation', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('specific_periods', 'project_nation')
    op.drop_column('specific_periods', 'project_link')
    # ### end Alembic commands ###
