"""empty message

Revision ID: 9855924da325
Revises: 373b4f80094f
Create Date: 2021-01-12 09:03:56.860685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9855924da325'
down_revision = '373b4f80094f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('project_content', sa.Text(), nullable=True))
    op.drop_column('specific_periods', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_column('specific_periods', 'project_content')
    # ### end Alembic commands ###
