"""empty message

Revision ID: a6be14b08c80
Revises: 5d04560d9aea
Create Date: 2021-01-12 10:12:30.565103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6be14b08c80'
down_revision = '5d04560d9aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('project_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specific_periods', 'project_content')
    # ### end Alembic commands ###
