"""empty message

Revision ID: c1b2addefc38
Revises: 2309488f9678
Create Date: 2021-01-12 17:24:25.921842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b2addefc38'
down_revision = '2309488f9678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specific_periods', sa.Column('apply_copi_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specific_periods', 'apply_copi_end_date')
    # ### end Alembic commands ###
