"""empty message

Revision ID: ce6af6d25608
Revises: 7c65e57f502d
Create Date: 2021-01-16 10:15:58.127683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6af6d25608'
down_revision = '7c65e57f502d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('COPI_project', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('COPI_project', 'accepted')
    # ### end Alembic commands ###
