"""empty message

Revision ID: e9b237d7ebf3
Revises: 0905f8ffe940
Create Date: 2021-01-20 06:54:36.382754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9b237d7ebf3'
down_revision = '0905f8ffe940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tel', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('webinfo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webinfo',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tel', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('webinfos')
    # ### end Alembic commands ###
